apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0 
  replicas: 10
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.39
        name: hello-http
        envFrom:
          - configMapRef:
              name: hello
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ENV
            value: "2"
        ports:
          - containerPort: 80
            name: http
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
          failureThreshold: 5
