apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: www
  name: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: nginx:1.26
        name: nginx-testa
        ports:
        - name: http
          containerPort: 80
        env:
          - name: STAGE
            value: K8S
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DAYS
            valueFrom:
              configMapKeyRef:
                name: www
                key: JOURS
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: www
                key: PASSWORD

        envFrom:
        - configMapRef:
            name: www
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          failureThreshold: 2
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d

      volumes:
      - name: html
        hostPath:
          path: /home/stagiaire/data/html
          type: Directory
      - name: nginx-conf
        hostPath:
          path: /home/stagiaire/data/nginx-conf
          type: Directory
